#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}
$appName = "
 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕

    Khunpra MIS Workflow Installer                           

 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕 🍔 🍟 🍕
";

$app = new Symfony\Component\Console\Application($appName, '0.0.1');
$app->add(new Khunpra\Installer\Console\NewCommand);
$app->run();